export const DISPLAY_SCREEN = 'STATE_DISPLAY_SCREEN';
export const COTYLE_PLANIFICATION= 'STATE_COTYLE_PLANIFICATION';
export const FEMUR_PLANIFICATION= 'STATE_FEMUR_PLANIFICATION';
export const PLANIFICATION= 'STATE_PLANIFICATION';
export const VALIDATE_PLANIFICATION= 'STATE_VALIDATE_PLANIFICATION';
